// Generated by scripts/refresh-jobs.mjs. Keep titles short, attributed, and link-out only.
export const jobFeedMeta = {
  "generatedAt": "2026-06-30T07:31:05.037Z",
  "jobCount": 50,
  "sourceCount": 8,
  "sources": [
    "Greenhouse: Duolingo",
    "Greenhouse: Later",
    "Greenhouse: Masterclass",
    "Greenhouse: Reddit",
    "Greenhouse: Spotter",
    "Remotive",
    "We Work Remotely",
    "Working Nomads"
  ]
};

export const liveJobs = [
  {
    "id": "everai-mid-senior-ai-cinematic-video-editor-worldwide-2026-06-24",
    "title": "Mid/Senior AI Cinematic Video Editor",
    "company": "EverAI",
    "location": "Worldwide",
    "dateListed": "2026-06-24",
    "sourceName": "Remotive",
    "sourceType": "public API",
    "sourceUrl": "https://remotive.com/remote-jobs/all-others/mid-senior-ai-cinematic-video-editor-2091035",
    "roleFamily": "Video editing",
    "confidence": "direct",
    "tags": [
      "excel",
      "video",
      "AI/ML",
      "customer acquisition"
    ]
  },
  {
    "id": "everai-limited-mid-senior-ai-cinematic-video-editor-full-remote-worldwide-worldw",
    "title": "Mid/Senior AI Cinematic Video Editor (Full Remote - Worldwide)",
    "company": "EverAI Limited",
    "location": "Worldwide, North America, South America, Asia, Europe, Africa, Oceania",
    "dateListed": "2026-06-24",
    "sourceName": "Working Nomads",
    "sourceType": "public API",
    "sourceUrl": "https://www.workingnomads.com/job/go/1687327/",
    "roleFamily": "Video editing",
    "confidence": "direct",
    "tags": [
      "video production",
      "creative",
      "graphic design",
      "communication"
    ]
  },
  {
    "id": "toureasy-d-o-o-content-creator-location-based-video-tours-eu-only-50-onboarding-",
    "title": "Content Creator - Location-Based Video Tours (EU Only) - 50 onboarding",
    "company": "Toureasy d.o.o.",
    "location": "Remote (EU-based creators only)",
    "dateListed": "2026-06-10",
    "sourceName": "Working Nomads",
    "sourceType": "public API",
    "sourceUrl": "https://www.workingnomads.com/job/go/1656359/",
    "roleFamily": "Creator content",
    "confidence": "near",
    "tags": [
      "travel",
      "content creation",
      "mobile"
    ]
  },
  {
    "id": "marker-video-content-creator-usa-canada-2026-06-03",
    "title": "Content Creator",
    "company": "Marker Video",
    "location": "USA, Canada",
    "dateListed": "2026-06-03",
    "sourceName": "Working Nomads",
    "sourceType": "public API",
    "sourceUrl": "https://www.workingnomads.com/job/go/1643275/",
    "roleFamily": "Video editing",
    "confidence": "near",
    "tags": [
      "editing",
      "media",
      "english",
      "social media"
    ]
  },
  {
    "id": "later-social-media-creative-network-freelance-remote-2026-06-12",
    "title": "Social Media Creative Network (Freelance)",
    "company": "Later",
    "location": "Remote",
    "dateListed": "2026-06-12",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8590104002",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": [
      "Services"
    ]
  },
  {
    "id": "later-social-media-manager-remote-2026-06-11",
    "title": "Social Media Manager",
    "company": "Later",
    "location": "Remote",
    "dateListed": "2026-06-11",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8582572002",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": [
      "Marketing"
    ]
  },
  {
    "id": "superplane-devrel-content-creator-remote-2026-05-14",
    "title": "DevRel - Content Creator",
    "company": "SuperPlane",
    "location": "Remote",
    "dateListed": "2026-05-14",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/superplane-devrel-content-creator",
    "roleFamily": "Creator content",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "duolingo-senior-product-designer-seattle-wa-2026-06-30",
    "title": "Senior Product Designer",
    "company": "Duolingo",
    "location": "Seattle, WA",
    "dateListed": "2026-06-30",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8489189002?gh_jid=8489189002",
    "roleFamily": "Design and motion",
    "confidence": "near",
    "tags": [
      "Product Design"
    ]
  },
  {
    "id": "duolingo-staff-product-designer-pittsburgh-pa-2026-06-30",
    "title": "Staff Product Designer",
    "company": "Duolingo",
    "location": "Pittsburgh, PA",
    "dateListed": "2026-06-30",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8200009002?gh_jid=8200009002",
    "roleFamily": "Design and motion",
    "confidence": "near",
    "tags": [
      "Product Design"
    ]
  },
  {
    "id": "duolingo-staff-product-designer-new-york-ny-2026-06-30",
    "title": "Staff Product Designer",
    "company": "Duolingo",
    "location": "New York, NY",
    "dateListed": "2026-06-30",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8200010002?gh_jid=8200010002",
    "roleFamily": "Design and motion",
    "confidence": "near",
    "tags": [
      "Product Design"
    ]
  },
  {
    "id": "reddit-creative-strategist-app-dev-new-york-city-ny-2026-06-30",
    "title": "Creative Strategist - App Dev",
    "company": "Reddit",
    "location": "New York City, NY",
    "dateListed": "2026-06-30",
    "sourceName": "Greenhouse: Reddit",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/reddit/jobs/7769002",
    "roleFamily": "Creative strategy",
    "confidence": "near",
    "tags": [
      "Global Client Solutions"
    ]
  },
  {
    "id": "reddit-creative-technologist-karmalab-new-york-city-ny-2026-06-30",
    "title": "Creative Technologist, KarmaLab",
    "company": "Reddit",
    "location": "New York City, NY",
    "dateListed": "2026-06-30",
    "sourceName": "Greenhouse: Reddit",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/reddit/jobs/7768983",
    "roleFamily": "Creative strategy",
    "confidence": "near",
    "tags": [
      "Global Client Solutions"
    ]
  },
  {
    "id": "duolingo-country-marketing-manager-turkey-remote-turkey-2026-06-29",
    "title": "Country Marketing Manager, Turkey",
    "company": "Duolingo",
    "location": "Remote - Turkey",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8448693002?gh_jid=8448693002",
    "roleFamily": "Creative adjacent",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-creative-director-marketing-new-york-ny-2026-06-29",
    "title": "Creative Director, Marketing",
    "company": "Duolingo",
    "location": "New York, NY",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8442932002?gh_jid=8442932002",
    "roleFamily": "Creative strategy",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-creative-director-marketing-london-england-2026-06-29",
    "title": "Creative Director, Marketing",
    "company": "Duolingo",
    "location": "London, England",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8442934002?gh_jid=8442934002",
    "roleFamily": "Creative strategy",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-creative-technology-manager-pittsburgh-pa-2026-06-29",
    "title": "Creative Technology Manager",
    "company": "Duolingo",
    "location": "Pittsburgh, PA",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8521468002?gh_jid=8521468002",
    "roleFamily": "Creative strategy",
    "confidence": "near",
    "tags": [
      "Design"
    ]
  },
  {
    "id": "duolingo-creative-technology-manager-new-york-ny-2026-06-29",
    "title": "Creative Technology Manager",
    "company": "Duolingo",
    "location": "New York, NY",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8521484002?gh_jid=8521484002",
    "roleFamily": "Creative strategy",
    "confidence": "near",
    "tags": [
      "Design"
    ]
  },
  {
    "id": "duolingo-regional-marketing-manager-mena-remote-dubai-2026-06-29",
    "title": "Regional Marketing Manager, MENA",
    "company": "Duolingo",
    "location": "Remote - Dubai",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8240009002?gh_jid=8240009002",
    "roleFamily": "Creative adjacent",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "reddit-creative-strategist-karmalab-london-united-kingdom-2026-06-18",
    "title": "Creative Strategist, KarmaLab",
    "company": "Reddit",
    "location": "London, United Kingdom",
    "dateListed": "2026-06-18",
    "sourceName": "Greenhouse: Reddit",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/reddit/jobs/8015790",
    "roleFamily": "Creative strategy",
    "confidence": "near",
    "tags": [
      "Global Client Solutions"
    ]
  },
  {
    "id": "spotter-campaign-operations-manager-culver-city-california-united-states-2026-06",
    "title": "Campaign Operations Manager",
    "company": "Spotter",
    "location": "Culver City, California, United States",
    "dateListed": "2026-06-12",
    "sourceName": "Greenhouse: Spotter",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/spotter/jobs/4705593005",
    "roleFamily": "Creative adjacent",
    "confidence": "near",
    "tags": [
      "Ad Sales"
    ]
  },
  {
    "id": "lemon-io-senior-ui-ux-graphic-designer-europe-north-america-latin-america-apac-2",
    "title": "Senior UI & UX / Graphic Designer",
    "company": "Lemon.io",
    "location": "Europe, North America, Latin America, APAC",
    "dateListed": "2026-06-11",
    "sourceName": "Working Nomads",
    "sourceType": "public API",
    "sourceUrl": "https://www.workingnomads.com/job/go/1658647/",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "ux designer",
      "figma",
      "product design",
      "graphic design"
    ]
  },
  {
    "id": "iapwe-freelance-writer-worldwide-2026-06-05",
    "title": "Freelance Writer",
    "company": "IAPWE",
    "location": "Worldwide",
    "dateListed": "2026-06-05",
    "sourceName": "Remotive",
    "sourceType": "public API",
    "sourceUrl": "https://remotive.com/remote-jobs/writing/freelance-writer-1185979",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": [
      "REST"
    ]
  },
  {
    "id": "animalz-senior-content-marketer-seo-remote-2026-06-05",
    "title": "Senior Content Marketer, SEO",
    "company": "Animalz",
    "location": "Remote",
    "dateListed": "2026-06-05",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/animalz-senior-content-marketer-seo",
    "roleFamily": "Creative adjacent",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "coalition-technologies-copywriter-worldwide-2026-06-03",
    "title": "Copywriter",
    "company": "Coalition Technologies",
    "location": "Worldwide",
    "dateListed": "2026-06-03",
    "sourceName": "Remotive",
    "sourceType": "public API",
    "sourceUrl": "https://remotive.com/remote-jobs/writing/copywriter-1749306",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": [
      "accounting",
      "excel",
      "research",
      "data analysis"
    ]
  },
  {
    "id": "north-spore-llc-head-of-marketing-remote-2026-04-22",
    "title": "Head of Marketing",
    "company": "North Spore LLC",
    "location": "Remote",
    "dateListed": "2026-04-22",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/north-spore-llc-head-of-marketing",
    "roleFamily": "Creative adjacent",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "hello-there-collective-affiliate-marketing-manager-remote-2026-03-18",
    "title": "Affiliate Marketing Manager",
    "company": "Hello There Collective",
    "location": "Remote",
    "dateListed": "2026-03-18",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/hello-there-collective-affiliate-marketing-manager",
    "roleFamily": "Creative adjacent",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "designfiles-content-marketing-coordinator-remote-2026-06-29",
    "title": "Content Marketing Coordinator",
    "company": "DesignFiles",
    "location": "Remote",
    "dateListed": "2026-06-29",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/designfiles-content-marketing-coordinator",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "duolingo-head-of-influencers-community-new-york-ny-2026-06-29",
    "title": "Head of Influencers & Community",
    "company": "Duolingo",
    "location": "New York, NY",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8548803002?gh_jid=8548803002",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-head-of-influencers-community-pittsburgh-pa-2026-06-29",
    "title": "Head of Influencers & Community",
    "company": "Duolingo",
    "location": "Pittsburgh, PA",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8548793002?gh_jid=8548793002",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-senior-community-manager-new-york-ny-2026-06-29",
    "title": "Senior Community Manager",
    "company": "Duolingo",
    "location": "New York, NY",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8385180002?gh_jid=8385180002",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-senior-community-manager-seattle-wa-2026-06-29",
    "title": "Senior Community Manager",
    "company": "Duolingo",
    "location": "Seattle, WA",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8345186002?gh_jid=8345186002",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-senior-community-manager-pittsburgh-pa-2026-06-29",
    "title": "Senior Community Manager",
    "company": "Duolingo",
    "location": "Pittsburgh, PA",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8524827002?gh_jid=8524827002",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "everai-limited-senior-performance-marketer-full-remote-worldwide-worldwide-north",
    "title": "Senior Performance Marketer (Full Remote - Worldwide)",
    "company": "EverAI Limited",
    "location": "Worldwide, North America, South America, Europe, Asia, Africa, Oceania",
    "dateListed": "2026-06-24",
    "sourceName": "Working Nomads",
    "sourceType": "public API",
    "sourceUrl": "https://www.workingnomads.com/job/go/1687329/",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": [
      "performance marketing",
      "customer acquisition",
      "advertising",
      "english"
    ]
  },
  {
    "id": "later-vp-creator-growth-slg-remote-2026-06-17",
    "title": "VP, Creator Growth (SLG)",
    "company": "Later",
    "location": "Remote",
    "dateListed": "2026-06-17",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8552394002",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "Creator Success"
    ]
  },
  {
    "id": "hologrowth-google-ads-media-buyer-growth-agency-dtc-ecommerce-remote-2026-06-10",
    "title": "Google Ads Media Buyer @ Growth Agency (DTC Ecommerce)",
    "company": "HoloGrowth",
    "location": "Remote",
    "dateListed": "2026-06-10",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/hologrowth-google-ads-media-buyer-growth-agency-dtc-ecommerce",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "later-director-creator-growth-plg-remote-2026-06-05",
    "title": "Director, Creator Growth (PLG)",
    "company": "Later",
    "location": "Remote",
    "dateListed": "2026-06-05",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8552402002",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": [
      "Creator Success"
    ]
  },
  {
    "id": "masterclass-sr-content-marketing-manager-united-states-remote-2026-06-03",
    "title": "Sr. Content Marketing Manager",
    "company": "Masterclass",
    "location": "United States (Remote)",
    "dateListed": "2026-06-03",
    "sourceName": "Greenhouse: Masterclass",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/masterclass/jobs/7979467",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": [
      "Marketing"
    ]
  },
  {
    "id": "binance-dach-community-manager-events-remote-2026-04-02",
    "title": "DACH Community Manager (Events)",
    "company": "Binance",
    "location": "Remote",
    "dateListed": "2026-04-02",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/binance-dach-community-manager-events",
    "roleFamily": "Creator partnerships",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "the-careside-performance-marketing-specialist-remote-2025-10-09",
    "title": "Performance Marketing Specialist",
    "company": "The CareSide",
    "location": "Remote",
    "dateListed": "2025-10-09",
    "sourceName": "We Work Remotely",
    "sourceType": "RSS",
    "sourceUrl": "https://weworkremotely.com/remote-jobs/the-careside-performance-marketing-specialist",
    "roleFamily": "Marketing content",
    "confidence": "near",
    "tags": []
  },
  {
    "id": "later-senior-paid-media-manager-social-boston-ma-2025-12-22",
    "title": "Senior Paid Media Manager (Social)",
    "company": "Later",
    "location": "Boston, MA",
    "dateListed": "2025-12-22",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8350790002",
    "roleFamily": "Marketing content",
    "confidence": "adjacent",
    "tags": [
      "Services"
    ]
  },
  {
    "id": "later-senior-paid-media-manager-social-new-york-new-york-united-states-2025-12-2",
    "title": "Senior Paid Media Manager (Social)",
    "company": "Later",
    "location": "New York, New York, United States",
    "dateListed": "2025-12-22",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8350787002",
    "roleFamily": "Marketing content",
    "confidence": "adjacent",
    "tags": [
      "Services"
    ]
  },
  {
    "id": "duolingo-staff-program-manager-brand-campaigns-new-york-ny-2026-06-29",
    "title": "Staff Program Manager Brand Campaigns",
    "company": "Duolingo",
    "location": "New York, NY",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8590229002?gh_jid=8590229002",
    "roleFamily": "Creative strategy",
    "confidence": "adjacent",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "duolingo-staff-program-manager-brand-campaigns-pittsburgh-pa-2026-06-29",
    "title": "Staff Program Manager Brand Campaigns",
    "company": "Duolingo",
    "location": "Pittsburgh, PA",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8590215002?gh_jid=8590215002",
    "roleFamily": "Creative strategy",
    "confidence": "adjacent",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "later-senior-ux-designer-remote-2026-06-16",
    "title": "Senior UX Designer",
    "company": "Later",
    "location": "Remote",
    "dateListed": "2026-06-16",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8372391002",
    "roleFamily": "Design and motion",
    "confidence": "adjacent",
    "tags": [
      "Product"
    ]
  },
  {
    "id": "later-senior-ux-designer-boston-ma-2026-06-16",
    "title": "Senior UX Designer",
    "company": "Later",
    "location": "Boston, MA",
    "dateListed": "2026-06-16",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8372380002",
    "roleFamily": "Design and motion",
    "confidence": "adjacent",
    "tags": [
      "Product"
    ]
  },
  {
    "id": "later-account-manager-creator-affiliate-boston-ma-2026-06-11",
    "title": "Account Manager - Creator Affiliate",
    "company": "Later",
    "location": "Boston, MA",
    "dateListed": "2026-06-11",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8584737002",
    "roleFamily": "Creative adjacent",
    "confidence": "adjacent",
    "tags": [
      "Services"
    ]
  },
  {
    "id": "later-account-manager-creator-affiliate-remote-2026-06-11",
    "title": "Account Manager - Creator Affiliate",
    "company": "Later",
    "location": "Remote",
    "dateListed": "2026-06-11",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8584739002",
    "roleFamily": "Creative adjacent",
    "confidence": "adjacent",
    "tags": [
      "Services"
    ]
  },
  {
    "id": "later-account-manager-creator-affiliate-new-york-new-york-united-states-2026-06-",
    "title": "Account Manager - Creator Affiliate",
    "company": "Later",
    "location": "New York, New York, United States",
    "dateListed": "2026-06-11",
    "sourceName": "Greenhouse: Later",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/later/jobs/8584738002",
    "roleFamily": "Creative adjacent",
    "confidence": "adjacent",
    "tags": [
      "Services"
    ]
  },
  {
    "id": "duolingo-performance-marketing-lead-new-york-ny-2026-06-29",
    "title": "Performance Marketing Lead",
    "company": "Duolingo",
    "location": "New York, NY",
    "dateListed": "2026-06-29",
    "sourceName": "Greenhouse: Duolingo",
    "sourceType": "official company board",
    "sourceUrl": "https://careers.duolingo.com/jobs/8562780002?gh_jid=8562780002",
    "roleFamily": "Marketing content",
    "confidence": "adjacent",
    "tags": [
      "Marketing and Communications"
    ]
  },
  {
    "id": "masterclass-sr-performance-marketing-manager-meta-california-usa-2026-06-24",
    "title": "Sr. Performance Marketing Manager, Meta",
    "company": "Masterclass",
    "location": "California, USA",
    "dateListed": "2026-06-24",
    "sourceName": "Greenhouse: Masterclass",
    "sourceType": "official company board",
    "sourceUrl": "https://job-boards.greenhouse.io/masterclass/jobs/8017915",
    "roleFamily": "Marketing content",
    "confidence": "adjacent",
    "tags": [
      "Marketing"
    ]
  }
];
